[package]
name = "nt"
version = "0.1.0"
authors = ["Redrield <redrield@gmail.com>"]

[dependencies]
tokio = "0.1.7"
bytes = "0.4.9"
nt-packet = { path = "./nt-packet" }
nt-packet-derive = { path = "./nt-packet-derive" }
failure = "0.1.2"
tokio-codec = "0.1.0"
futures = "0.1.23"
log = "0.4.3"
tokio-core = "0.1.17"
