[package]
name = "nt"
version = "0.3.1"
authors = ["Redrield <redrield@gmail.com>"]

description = "A NetworkTables revision 3 client library for Rust"
license = "MIT"
repository = "https://gitlab.com/Redrield/nt-rs"

[dependencies]
tokio = "0.1.7"
bytes = "0.4.9"
nt-packet = "0.1.2"
nt-packet-derive = "0.1.4"
failure = "0.1.2"
tokio-codec = "0.1.0"
futures = "0.1.23"
log = "0.4.3"
tokio-core = "0.1.17"
derive-new = "0.5.5"
fern = "0.5.6"
chrono = "0.4.5"
multimap = "0.4.0"
serde = { version = "1.0.79", optional = true, features = ["derive"] }


[dependencies.nt-leb128]
version = "0.2.4"
default-features = false
features = ["use-bytes"]

[features]
default = ["serde"]
