[package]
name = "nt"
version = "1.0.0"
authors = ["Redrield <redrield@gmail.com>"]
description = "A NetworkTables revision 3 library for Rust"
license = "MIT"
repository = "https://gitlab.com/Redrield/nt-rs"
edition = "2018"

[dependencies]
tokio = "0.1.19"
bytes = "0.4.12"
failure = "0.1.5"
nt-network = "1.0.0"
crossbeam-channel = "0.3.8"
log = "0.4.6"
fern = "0.5.8"
chrono = "0.4.6"
futures = "0.1.27"
multimap = "0.5.0"
websocket = { version = "0.22.4", optional = true }

[dependencies.nt-leb128]
version = "0.2.4"
default-features = false
features = ["use-bytes"]
