[package]
name = "nt"
version = "1.0.3"
authors = ["Redrield <redrield@gmail.com>"]
description = "A NetworkTables revision 3 library for Rust"
license = "MIT"
repository = "https://gitlab.com/Redrield/nt-rs"
edition = "2018"

[dependencies]
tokio = { version = "0.2.6", features = ["full"] }
bytes = "0.4.12"
failure = "0.1.5"
nt-network = { path = "./nt-network" }
log = "0.4.6"
fern = "0.5.8"
multimap = "0.5.0"
#websocket = { version = "0.22.4", optional = true, default-features = false, features = ["async"] }
async-trait = "0.1.19"
nt-leb128 = "0.3.0"
futures-channel = "0.3.1"
futures-util = { version = "0.3.1", features = ["sink"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
