[package]
name = "nt-test"
version = "0.1.0"
authors = ["Redrield <redrield@gmail.com>"]

[dependencies]
nt = { path = "../" }
tokio = "0.1.7"
fern = "0.5.6"
log = "0.4.3"
failure = "0.1.2"
chrono = "0.4.5"
tokio-codec = "0.1.0"
futures = "0.1.23"
